parameters:
    ezpublish.fieldType.ezcolor.class: Simplelogica\EzColorFieldBundle\FieldType\EzColor\Type
    ezrepoforms.field_type.form_mapper.ezcolor.class: Simplelogica\EzColorFieldBundle\FieldType\EzColor\FormMapper

services:
    ezpublish.fieldType.ezcolor:
        class: "%ezpublish.fieldType.ezcolor.class%"
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezcolor}

    ezrepoforms.field_type.form_mapper.ezcolor:
        class: "%ezrepoforms.field_type.form_mapper.ezcolor.class%"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: ezcolor }
            - { name: ez.fieldFormMapper.value, fieldType: ezcolor }
        arguments:
            - "@ezpublish.api.service.field_type"

