parameters:
    ezpublish.fieldType.indexable.ezcolor.class: Simplelogica\EzColorFieldBundle\FieldType\EzColor\SearchField

services:
    ezpublish.fieldType.indexable.ezcolor:
        class: "%ezpublish.fieldType.indexable.ezcolor.class%"
        tags:
            - {name: ezpublish.fieldType.indexable, alias: ezcolor}
