system:
    default:
        yui:
            modules:
                ez-rawcontentview:
                    requires:
                        - 'ezcolor-ezcolor-view'
                ez-contenteditformview:
                    requires:
                        - 'ezcolor-ezcolor-editview'
                ezcolor-ezcolor-view:
                    requires: ['ez-fieldview', 'ezcolorview-ez-template']
                    path: "%ezcolor_ezcolorfieldtype.public_dir%/js/views/fields/ezcolor-ezcolor-view.js"
                ezcolor-ezcolor-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange', 'ezcoloreditview-ez-template']
                    path: "%ezcolor_ezcolorfieldtype.public_dir%/js/views/fields/ezcolor-ezcolor-editview.js"
                ezcolorview-ez-template:
                    type: 'template'
                    path: "%ezcolor_ezcolorfieldtype.public_dir%/templates/fields/view/ezcolor.hbt"
                ezcoloreditview-ez-template:
                    type: 'template'
                    path: "%ezcolor_ezcolorfieldtype.public_dir%/templates/fields/edit/ezcolor.hbt"




